SoftwareVentas/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SoftwareVentas.Data;
using SoftwareVentas.Data.Entities;

// Here we define the controller
namespace SoftwareVentas.Controllers
{
    public class CustomersController : Controller
    {
        private readonly DataContext _context;

        public CustomersController(DataContext context)
        {
            _context = context;
        }

        // Here we do the read method
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<Customer> customers = await _context.Customers.ToListAsync();
            return View(customers);
        }

        // Here we make the form to create a new client
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // Here we check if the model is valid
        [HttpPost]
        public async Task<IActionResult> Create(Customer customer)
        {
            if (!ModelState.IsValid)
            {
                return View(customer);
            }

            await _context.Customers.AddAsync(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //Here we look for the client id so we can move on to the edit view
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var customer = await _context.Customers.FindAsync(id);
            if (customer == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(customer);
        }

        //Here we verify that it is valid to be able to perform the update
        [HttpPost]
        public async Task<IActionResult> Edit(Customer customer)
        {
            if (!ModelState.IsValid)
            {
                return View(customer);
            }

            _context.Customers.Update(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // Here what we do is find a client by the id and delete it
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var customer = await _context.Customers.FindAsync(id);
            if (customer == null)
            {
                return RedirectToAction(nameof(Index));
            }

            _context.Customers.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

SoftwareVentas/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SoftwareVentas.Core.Pagination;
using SoftwareVentas.Data.Entities;
using SoftwareVentas.Models;

namespace SoftwareVentas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SoftwareVentas/Controllers/UsersController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using SoftwareVentas.Core;
using SoftwareVentas.Core.Atributtes;
using SoftwareVentas.Core.Pagination;
using SoftwareVentas.Data.Entities;
using SoftwareVentas.DTOs;
using SoftwareVentas.Helpers;
using SoftwareVentas.Services;
using System.Data;

namespace SoftwareVentas.Controllers
{
	public class UserController : Controller
	{
		private readonly IUsersService _usersService;
		private readonly IRoleService _roleService;
        private readonly INotyfService _notifyService;
        private readonly IConverterHelper _converterHelper;
        private readonly ICombosHelper _combosHelper;
        public UserController(IUsersService usersService, IRoleService roleService, INotyfService notifyService, IConverterHelper converterHelper, ICombosHelper combosHelper)
        {
            _usersService = usersService;
            _roleService = roleService;  // Inyecta el servicio _roleService
            _notifyService = notifyService;
            _converterHelper = converterHelper;
            _combosHelper = combosHelper;
        }

        [HttpGet]
        [CustomAuthorize(permission: "showUsers", module: "Users")]
        public async Task<IActionResult> Index([FromQuery] int? RecordsPerPage,
                                               [FromQuery] int? Page,
                                               [FromQuery] string? Filter)
        {
            PaginationRequest request = new PaginationRequest
            {
                RecordsPerPage = RecordsPerPage ?? 15,
                Page = Page ?? 1,
                Filter = Filter
            };

            Core.Response<PaginationResponse<User>> response = await _usersService.GetListAsync(request);
            return View(response.Result);
        }

        [HttpGet]
        [CustomAuthorize(permission: "createUsers", module: "Users")]
        public async Task<IActionResult> Create()
        {
            UserDTO dto = new UserDTO
            {
                Roles = await _combosHelper.GetComboSoftwareVentasRolesAsync(),
            };

            return View(dto);
        }

        [HttpPost]
        [CustomAuthorize(permission: "createUsers", module: "Users")]
        public async Task<IActionResult> Create(UserDTO dto)
		{
            try
            {
                if (!ModelState.IsValid)
                {
                    _notifyService.Error("Debe ajustar los errores de validación");
                    dto.Roles = await _combosHelper.GetComboSoftwareVentasRolesAsync();
                    foreach (var key in ModelState.Keys)
                    {
                        var state = ModelState[key];
                        foreach (var error in state.Errors)
                        {
                            Console.WriteLine($"Propiedad: {key}, Error: {error.ErrorMessage}");
                        }
                    }
                    return View(dto);
                }

                Response<User> response = await _usersService.CreateAsync(dto);

                if (response.IsSuccess)
                {
                    _notifyService.Success(response.Message);
                    return RedirectToAction(nameof(Index));
                }

                _notifyService.Error(response.Message);
                dto.Roles = await _combosHelper.GetComboSoftwareVentasRolesAsync();
                return View(dto);
            }
            catch (Exception ex)
            {
                dto.Roles = await _combosHelper.GetComboSoftwareVentasRolesAsync();
                return View(dto);
            }

        }
		[HttpGet]
        [CustomAuthorize(permission: "editUsers", module: "Users")]
        public async Task<IActionResult> Edit(Guid id)
		{
            if (Guid.Empty.Equals(id))
            {
                return NotFound();
            }

            User user = await _usersService.GetUserAsync(id);

            if (user is null)
            {
                return NotFound();
            }
            UserDTO dto = await _converterHelper.ToUserDTOAsync(user, false);

            return View(dto);
        }
		[HttpPost]
		[ValidateAntiForgeryToken]
        [CustomAuthorize(permission: "editUsers", module: "Users")]
        public async Task<IActionResult> Edit(UserDTO dto)
		{
            if (!ModelState.IsValid)
            {
                _notifyService.Error("Debe ajustar los errores de validación");
                dto.Roles = await _combosHelper.GetComboSoftwareVentasRolesAsync();
                return View(dto);
            }

            Response<User> response = await _usersService.UpdateUserAsync(dto);

            if (response.IsSuccess)
            {
                _notifyService.Success(response.Message);
                return RedirectToAction(nameof(Index));
            }

            _notifyService.Error(response.Message);
            dto.Roles = await _combosHelper.GetComboSoftwareVentasRolesAsync();
            return View(dto);
        }

	}
}

SoftwareVentas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Menú de Secciones";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}

<div id="content">

    <!-- Begin Page Content -->
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-flex justify-content-center mb-4">
            <h1 class="h3 mb-0 text-gray-800">Menú de Secciones</h1>
        </div>

        <!-- Content Row for Sections (Products, Users, etc.) -->
        <div class="row justify-content-center">

            <!-- Products Card -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body text-center">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Products
                        </div>
                        <a class="nav-link" asp-controller="Products" asp-action="Index">
                            <i class="fas fa-fw fa-tshirt"></i>
                            <span>Products</span>
                        </a>
                    </div>
                </div>
            </div>

            <!-- Users Card -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-success shadow h-100 py-2">
                    <div class="card-body text-center">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            Customers
                        </div>
                        <a class="nav-link" asp-controller="Customers" asp-action="Index">
                            <i class="fas fa-fw fa-users"></i>
                            <span>Customers</span>
                        </a>
                    </div>
                </div>
            </div>

            <!-- Orders Card -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-info shadow h-100 py-2">
                    <div class="card-body text-center">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                            Users
                        </div>
                        <a class="nav-link" asp-controller="User" asp-action="Index">
                            <i class="fas fa-fw fa-user"></i>
                            <span>Users</span>
                        </a>
                    </div>
                </div>
            </div>

            <!-- Orders Card -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-info shadow h-100 py-2">
                    <div class="card-body text-center">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                            Employees
                        </div>
                        <a class="nav-link" asp-controller="Employees" asp-action="Index">
                            <i class="fas fa-fw fa-user"></i>
                            <span>Employees</span>
                        </a>
                    </div>
                </div>
            </div>

            <!-- Reports Card -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-warning shadow h-100 py-2">
                    <div class="card-body text-center">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                            Roles
                        </div>
                        <a class="nav-link" asp-controller="Roles" asp-action="Index">
                            <i class="fas fa-fw fa-user"></i>
                            <span>Roles</span>
                        </a>
                    </div>
                </div>
            </div>

            <!-- Reports Card -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-warning shadow h-100 py-2">
                    <div class="card-body text-center">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                            Sales
                        </div>
                        <a class="nav-link" asp-controller="Sales" asp-action="Index">
                            <i class="fas fa-fw fa-user"></i>
                            <span>Sales</span>
                        </a>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>